# Build the NuGet package
parameters:
  - name: BuildConfiguration
    type: string
  - name: BuildVersion
    type: string
  - name: OfficialBuild
    type: boolean
    default: false

jobs:
  - job:
    pool:
      type: windows
    
    variables:
      ob_outputDirectory: '$(Build.SourcesDirectory)\out'
      # ob_nugetPublishing_enabled: ${{ parameters.OfficialBuild }}
      PackageVersion: ${{ parameters.BuildVersion }}

    steps:
      - task: UseDotNet@2
        continueOnError: true
        inputs: 
          packageType: 'runtime'
          version: '6.x'
          performMultiLevelLookup: true

      - task: NuGetToolInstaller@1
        displayName: Use NuGet 6.0.2
        continueOnError: True
        inputs:
          versionSpec: 6.0.2

      - task: DownloadPipelineArtifact@1
        displayName: 'Download x86 artifacts'
        inputs:
          artifactName: 'drop_build_x86'
          targetPath: '$(Build.SourcesDirectory)/x86'

      - task: DownloadPipelineArtifact@1
        displayName: 'Download x64 artifacts'
        inputs:
          artifactName: 'drop_build_x64'
          targetPath: '$(Build.SourcesDirectory)/x64'

      - task: DownloadPipelineArtifact@1
        displayName: 'Download arm artifacts'
        inputs:
          artifactName: 'drop_build_arm'
          targetPath: '$(Build.SourcesDirectory)/arm'

      - task: DownloadPipelineArtifact@1
        displayName: 'Download arm64 artifacts'
        inputs:
          artifactName: 'drop_build_arm64'
          targetPath: '$(Build.SourcesDirectory)/arm64'
            
      - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
        displayName: 'Build NuGet package'
        inputs:
          command: 'custom'
          arguments: 'pack nuget/Microsoft.Windows.CppWinRT.nuspec -NonInteractive -OutputDirectory $(ob_outputDirectory)\packages -Properties Configuration=release;cppwinrt_exe=C:\__w\1\s\x86\cppwinrt\cppwinrt.exe;cppwinrt_fast_fwd_x86=C:\__w\1\s\x86\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_x64=C:\__w\1\s\x64\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm=C:\__w\1\s\arm\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm64=C:\__w\1\s\arm64\cppwinrt_fast_forwarder.lib;target_version=$(PackageVersion) -Version $(PackageVersion) -Verbosity Detailed'

      # C:\hostedtoolcache\windows\NuGet\5.3.1\x64\nuget.exe push D:\a\_work\1\a\Microsoft.Windows.CsWinRT.2.0.7-prerelease.240311.1.nupkg -NonInteractive -Source https://microsoft.pkgs.visualstudio.com/_packaging/CsWinRT/nuget/v3/index.json -ApiKey VSTS

      # - task: NuGetCommand@2
      #   displayName: 'Build NuGet package'
      #   inputs:
      #     command: 'pack'
      #     packagesToPack: 'nuget/Microsoft.Windows.CppWinRT.nuspec'
      #     versioningScheme: byEnvVar
      #     versionEnvVar: 'PackageVersion'
      #     buildProperties: 'cppwinrt_exe=$(Build.SourcesDirectory)\x86\cppwinrt\cppwinrt.exe;cppwinrt_fast_fwd_x86=$(Build.SourcesDirectory)\x86\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_x64=$(Build.SourcesDirectory)\x64\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm=$(Build.SourcesDirectory)\arm\cppwinrt_fast_forwarder.lib;cppwinrt_fast_fwd_arm64=$(Build.SourcesDirectory)\arm64\cppwinrt_fast_forwarder.lib'
      #     packDestination: $(ob_outputDirectory)\packages

      - task: onebranch.pipeline.signing@1
        displayName: '🔒 Onebranch Signing for NuGet package'
        condition: eq(${{ parameters.OfficialBuild }}, 'true')
        inputs:
          command: sign
          signing_profile: external_distribution
          files_to_sign: 'Microsoft.Windows.CppWinRT.*.nupkg'
          search_root: $(ob_outputDirectory)\packages

      # - task: PkgESNuGetPublisher@0
      #   displayName: Publish NuGet Package
      #   inputs:
      #     searchPattern: $(ob_outputDirectory)\packages\Microsoft.Windows.CppWinRT.$(PackageVersion).nupkg
      #     nuGetFeedType: internal
      #     feedName: https://microsoft.pkgs.visualstudio.com/_packaging/CppWinRT/nuget/v3/index.json
